#!/usr/bin/env ruby

require "secret_keys_rails/commands/secret_keys_command"

rails_root = if ENV["RAILS_ROOT"]
  Pathname.new(ENV["RAILS_ROOT"]).expand_path
elsif File.exist?(File.join(Dir.pwd, "config/environment.rb"))
  Pathname.new(Dir.pwd)
elsif ENV["BUNDLE_GEMFILE"] && File.exist?(File.expand_path("../config/environment.rb", ENV["BUNDLE_GEMFILE"]))
  Pathname.new(File.expand_path("..", ENV["BUNDLE_GEMFILE"]))
else
  Pathname.new(Dir.pwd).expand_path
end

Dir.chdir(rails_root) do
  SecretKeysRails::Commands::SecretKeysCommand.start(ARGV)
end
