name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7"]
        rails: ["5.0", "5.1", "5.2", "6.0"]
        include:
          - ruby: "2.4"
            rails: "4.2"
    name: "test (Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }})"
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      BUNDLE_CLEAN: "true"
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.rails }}-gems-${{ hashFiles(env.BUNDLE_GEMFILE) }}
          restore-keys: ${{ runner.os }}-${{ matrix.rails }}-gems-
      - name: Bundler Downgrade
        run: |
          gem uninstall bundler -x
          gem install bundler -v "< 2" --no-document
        if: ${{ matrix.rails == '4.2' }}
      - name: Bundle Install
        run: bundle install
      - name: Test
        run: bundle exec rake test
